# Default Configuration

spring:
    profiles:
        active: dev

    main:
        banner-mode: "off"

    # TODO: check this stuff
    kafka:
        consumer:
            group-id: "executor_service"
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring:
                    json:
                        use.type.headers: false
                        value.default.type: com.bellotapps.the_messenger.commons.Message
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring:
                    json:
                        add.type.headers: false


code-runner:
    pre-run:
        command: "echo"
        args:
            - "\"Pre-run is Working!\""
        timeout: 10000
        continue-on-non-zero-exit-code: false
    runner:
        command: "echo"
        args:
            - "\"Runner is Working!\""
        default-timeout: 10000
    base-working-directory: "/tmp"



---
# Configuration for Development Environment

spring:
    profiles:
        - dev
        - development

    # TODO: check this stuff
    kafka:
        bootstrap-servers: localhost:9092

---
# Configuration for Staging Environment

spring:
    profiles:
        - staging

---
# Configuration for Production Environment

spring:
    profiles:
        - prod
        - production
